version: '3.9'

services:
  db:
    image: postgres:16
    container_name: odometra-db
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - odometra-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: odometra-pgadmin
    restart: always
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - odometra-net

  backend:
    build: ./backend
    container_name: odometra-backend
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - odometra-net

volumes:
  db_data:

networks:
  odometra-net:
